sudo: false
language: bash
env:
  global:
    - BR_RELEASE=2015.08-rc1.rev2
addons:
  apt:
    packages:
    - build-essential
    - libncurses5-dev
    - rsync
    - cpio
    - python
    - unzip
    - bc
    - wget
install:
  - if [ -f ${$TRAVIS_BUILD_DIR}/.travis.yml.install ]; then bash -e ${$TRAVIS_BUILD_DIR}/.travis.yml.install; fi
  - bash -e $(dirname $(readlink -f ${TRAVIS_BUILD_DIR}/.travis.yml))/install
script:
  - if [ -f ${$TRAVIS_BUILD_DIR}/.travis.yml.script ]; then bash -e ${$TRAVIS_BUILD_DIR}/.travis.yml.script; fi
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/script
after_failure:
  - if [ -f ${$TRAVIS_BUILD_DIR}/.travis.yml.after_failure ]; then bash -e ${$TRAVIS_BUILD_DIR}/.travis.yml.after_failure; fi
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/after_failure
after_success:
  - if [ -f ${$TRAVIS_BUILD_DIR}/.travis.yml.after_success ]; then bash -e ${$TRAVIS_BUILD_DIR}/.travis.yml.after_success; fi
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/after_success
