sudo: false
language: bash
env:
  global:
    - BR_RELEASE=2015.08-rc1.rev2
addons:
  apt:
    packages:
    - build-essential
    - libncurses5-dev
    - rsync
    - cpio
    - python
    - unzip
    - bc
    - wget
install:
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/install
script:
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/script
after_failure:
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/after_failure
after_success:
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/after_success
